from typing import Final

#final transforma variavel em constante

NOME_MAX_LENGTH: Final = 150
RAZAO_SOCIAL_MAX_LENGTH: Final = 200
EMAIL_MAX_LENGTH: Final = 255
SENHA_HASH_MAX_LENGTH: Final = 255
TELEFONE_MAX_LENGTH: Final = 20
URL_MAX_LENGTH: Final = 500
SLUG_MAX_LENGTH: Final = 150
DOCUMENTO_MAX_LENGTH: Final = 20
SEGMENTO_MAX_LENGTH: Final = 100
CARGO_MAX_LENGTH: Final = 100
ICONE_MAX_LENGTH: Final = 50
TITULO_MAX_LENGTH: Final = 200
CATEGORIA_MAX_LENGTH: Final = 100
PAPEL_MAX_LENGTH: Final = 80
ORCAMENTO_MAX_LENGTH: Final = 50
TIPO_ARQUIVO_MAX_LENGTH: Final = 50
USER_AGENT_MAX_LENGTH: Final = 255
CHAVE_INTEGRACAO_MAX_LENGTH: Final = 255
ACAO_XP_MAX_LENGTH: Final = 150

PROGRESSO_MIN: Final = 0
PROGRESSO_MAX: Final = 100
XP_MIN: Final = 0

NIVEL_FUNCIONARIO_INICIAL: Final = 1
NIVEL_ACESSO_INICIAL: Final = 1
XP_INICIAL: Final = 0

DURACAO_EVENTO_PADRAO_MIN: Final = 60

PAGINATION_DEFAULT_LIMIT: Final = 50
PAGINATION_MAX_LIMIT: Final = 200
PAGINATION_DEFAULT_OFFSET: Final = 0

JWT_DEFAULT_ALGORITHM: Final = 'HS256'
JWT_ACCESS_TOKEN_EXPIRE_MIN: Final = 60
JWT_REFRESH_TOKEN_EXPIRE_DAYS: Final = 7

PRECO_DECIMAL_PLACES: Final = 2
PRECO_TOTAL_DIGITS: Final = 10