from typing import Final

TAMANHO_MAXIMO_NOME: Final = 150
TAMANHO_MAXIMO_RAZAO_SOCIAL: Final = 200
TAMANHO_MAXIMO_EMAIL: Final = 255
TAMANHO_MAXIMO_HASH_SENHA: Final = 255
TAMANHO_MAXIMO_TELEFONE: Final = 20
TAMANHO_MAXIMO_URL: Final = 500
TAMANHO_MAXIMO_SLUG: Final = 150
TAMANHO_MAXIMO_DOCUMENTO: Final = 20
TAMANHO_MAXIMO_SEGMENTO: Final = 100
TAMANHO_MAXIMO_CARGO: Final = 100
TAMANHO_MAXIMO_ICONE: Final = 50
TAMANHO_MAXIMO_TITULO: Final = 200
TAMANHO_MAXIMO_CATEGORIA: Final = 100
TAMANHO_MAXIMO_PAPEL: Final = 80
TAMANHO_MAXIMO_ORCAMENTO: Final = 50
TAMANHO_MAXIMO_TIPO_ARQUIVO: Final = 50
TAMANHO_MAXIMO_AGENTE_USUARIO: Final = 255
TAMANHO_MAXIMO_CHAVE_INTEGRACAO: Final = 255
TAMANHO_MAXIMO_ACAO_XP: Final = 150

PROGRESSO_MINIMO: Final = 0
PROGRESSO_MAXIMO: Final = 100
XP_MINIMO: Final = 0

NIVEL_FUNCIONARIO_INICIAL: Final = 1
NIVEL_ACESSO_INICIAL: Final = 1
XP_INICIAL: Final = 0

DURACAO_MINIMA_EVENTO_PADRAO: Final = 60

LIMITE_PADRAO_PAGINACAO: Final = 50
LIMITE_MAXIMO_PAGINACAO: Final = 200
DESLOCAMENTO_PADRAO_PAGINACAO: Final = 0

ALGORITMO_PADRAO_JWT: Final = 'HS256'
MINUTOS_EXPIRACAO_TOKEN_ACESSO_JWT: Final = 60
DIAS_EXPIRACAO_TOKEN_ATUALIZACAO_JWT: Final = 7

CASAS_DECIMAIS_PRECO: Final = 2
DIGITOS_TOTAIS_PRECO: Final = 10
